services:
  postgres:
    image: postgres:16-alpine
    environment:
      - 'POSTGRES_DB=task_api'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
